---
galaxy_info:
  role_name: vuln_adcs
  author: DVAD
  description: Configures ADCS ESC1-ESC13/ESC15 attack-vector templates and CA-level misconfigurations
  min_ansible_version: "2.12"
  platforms:
    - name: Windows
      versions:
        - 2019
        - 2022

dependencies: []
