---
galaxy_info:
  role_name: child_domain
  author: EMPIRE
  description: Promotes a Windows Server to DC for the eu.empire.local child domain
  min_ansible_version: "2.12"
  platforms:
    - name: Windows
      versions:
        - 2019
        - 2022

dependencies: []
