---
galaxy_info:
  role_name: dns
  author: DVAD
  description: Configures DNS forwarders and conditional forwarders between DVAD forests
  min_ansible_version: "2.12"
  platforms:
    - name: Windows
      versions:
        - 2019
        - 2022

dependencies: []
