#!/usr/bin/env bash
# setup-sudoers.sh — Write NOPASSWD sudoers for EMPIRE lab network/VM operations.
# Required for cron and non-interactive deploys that call providers/qemu scripts.
#
# Usage:
#   bash scripts/setup-sudoers.sh              # install for current user
#   bash scripts/setup-sudoers.sh --user alice # install for specific user
#   bash scripts/setup-sudoers.sh --remove     # remove the drop-in
set -euo pipefail
IFS=$'\n\t'

SUDOERS_FILE="/etc/sudoers.d/empire-lab"

log()  { echo -e "\033[0;32m[+]\033[0m $*"; }
warn() { echo -e "\033[1;33m[!]\033[0m $*"; }
err()  { echo -e "\033[0;31m[x]\033[0m $*"; }

DEPLOY_USER="${USER}"
REMOVE=false

while [[ $# -gt 0 ]]; do
    case "$1" in
        --user)  DEPLOY_USER="$2"; shift 2 ;;
        --remove) REMOVE=true; shift ;;
        *) err "Unknown option: $1"; exit 1 ;;
    esac
done

if $REMOVE; then
    if [[ -f "$SUDOERS_FILE" ]]; then
        sudo rm -f "$SUDOERS_FILE"
        log "Removed $SUDOERS_FILE"
    else
        warn "$SUDOERS_FILE not found — nothing to remove."
    fi
    exit 0
fi

# Resolve binary paths at install time — handles /usr/sbin vs /sbin differences
resolve() {
    command -v "$1" 2>/dev/null || echo "/usr/sbin/$1"
}

IP_BIN="$(resolve ip)"
NFT_BIN="$(resolve nft)"
IPT_BIN="$(resolve iptables)"
SYSCTL_BIN="$(resolve sysctl)"
TEE_BIN="$(resolve tee)"
GREP_BIN="$(resolve grep)"
MKDIR_BIN="$(resolve mkdir)"
KILL_BIN="$(resolve kill)"
PKILL_BIN="$(resolve pkill)"
SED_BIN="$(resolve sed)"
DNSMASQ_BIN="$(resolve dnsmasq)"

CONTENT="# EMPIRE lab — NOPASSWD for ${DEPLOY_USER}
# Generated by scripts/setup-sudoers.sh on $(date -Iseconds)
# Remove: sudo rm ${SUDOERS_FILE}

Cmnd_Alias EMPIRE_NET = \\
    ${IP_BIN}, \\
    ${NFT_BIN}, \\
    ${IPT_BIN}, \\
    ${SYSCTL_BIN}, \\
    ${TEE_BIN}, \\
    ${GREP_BIN}, \\
    ${MKDIR_BIN}, \\
    ${KILL_BIN}, \\
    ${PKILL_BIN}, \\
    ${SED_BIN}, \\
    ${DNSMASQ_BIN}

${DEPLOY_USER} ALL=(root) NOPASSWD: EMPIRE_NET
"

# Validate with visudo before writing
TMPFILE="$(mktemp /tmp/empire-sudoers.XXXXXX)"
printf '%s' "$CONTENT" > "$TMPFILE"

if ! sudo visudo -cf "$TMPFILE" 2>&1; then
    err "sudoers validation failed. Not writing to ${SUDOERS_FILE}."
    rm -f "$TMPFILE"
    exit 1
fi

sudo cp "$TMPFILE" "$SUDOERS_FILE"
sudo chmod 440 "$SUDOERS_FILE"
rm -f "$TMPFILE"

log "Written: ${SUDOERS_FILE}"
log "User '${DEPLOY_USER}' can now run QEMU/network commands without password."
log ""
log "Verify with:  sudo -n ip link show"
log "Remove with:  bash scripts/setup-sudoers.sh --remove"
